// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB1PZdPMdN4NkZyNEDCEd0MRbUaWF8Jdo',
    appId: '1:836583958038:web:b0f6dff55fbf142035b737',
    messagingSenderId: '836583958038',
    projectId: 'living-way-staging',
    authDomain: 'living-way-staging.firebaseapp.com',
    storageBucket: 'living-way-staging.firebasestorage.app',
    measurementId: 'G-VP8V9E2XC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAggkJrRrNHzIRBYKYYTbxhfofQY3r_HBY',
    appId: '1:836583958038:android:58f2786922a27b3b35b737',
    messagingSenderId: '836583958038',
    projectId: 'living-way-staging',
    storageBucket: 'living-way-staging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARjY33UcZLpvPveg6moMW9bWjm-FPMRy8',
    appId: '1:836583958038:ios:7a836af3cbde35c735b737',
    messagingSenderId: '836583958038',
    projectId: 'living-way-staging',
    storageBucket: 'living-way-staging.firebasestorage.app',
    iosBundleId: 'com.livingway.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARjY33UcZLpvPveg6moMW9bWjm-FPMRy8',
    appId: '1:836583958038:ios:58f46feb0a44970735b737',
    messagingSenderId: '836583958038',
    projectId: 'living-way-staging',
    storageBucket: 'living-way-staging.firebasestorage.app',
    iosBundleId: 'com.livingway.app.RunnerTests',
  );
}
